fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    registration:
        confirmation:
            enabled: true
        form:
            type: App\Form\Type\RegistrationFormType
    from_email:
        address: "noreply@omusvi.com"
        sender_name: "noreply@pitacare.com"