vich_uploader:
    db_driver: orm

    mappings:
       my_event_image: 
           uri_prefix: /images/my_event
           upload_destination: '%kernel.project_dir%/public/images/my_event'

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true